blank_issues_enabled: true
contact_links:
  - name: Security Issues
    url: https://github.com/cascadiacollections/sir-chrome-extension/security/advisories/new
    about: Please report security vulnerabilities through GitHub's security advisory feature
  - name: Discussions
    url: https://github.com/cascadiacollections/sir-chrome-extension/discussions
    about: Ask questions and discuss ideas with the community