name: main CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: latest
      - run: yarn install
      - run: yarn build
      - run: yarn test
      - name: Move scripts to release folder
        run: mv dist/ app/
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: sir-chrome-extension
          path: app/